name: Build
on:
  push:
    branches: [main, dev, 'research', 'research/**']
    tags: ['v*.*.*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dioptra-io/publish-docker-action@v1
        with:
          file: ./Dockerfile
          image: dioptra-io/retina-orchestrator
          password: ${{ secrets.GITHUB_TOKEN }}
          push: true
